definitions:
  # 自动殖民算法
  colony_automation:
    title: Colony Automation
    type: object
    properties:
      available:
        $ref: "core.yaml/#/definitions/conditions"
      prio_districts:
        $type: district[]
      buildings:
        type: object
        propertyNames:
          $ref: "core.yaml/#/definitions/uint"
        additionalProperties:
          type: object
          properties:
            # anyOf (building, available)
            bulding:
              $type: building
            available:
              $ref: "core.yaml/#/definitions/conditions"

title: Colony Automation
type: object
additionalProperties:
  $ref: "#/definitions/colony_automation"
