definitions:
  # 自动殖民算法
  colony_automation:
    type: object
    properties:
      available:
        $ref: "../core.yaml#/definitions/conditions"
      prio_districts:
        type: array
        items:
          $type: "district"
      buildings:
        type: object
        propertyNames:
          $ref: "../core.yaml#/definitions/int"
        additionalProperties:
          type: object
          properties:
            bulding:
              $type: "building"
              multiple: true
            available:
              $ref: "../core.yaml#/definitions/conditions"

type: object
additionalProperties:
  $ref: "#/definitions/colony_automation"
